name: bumpwright auto bump

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

concurrency:
  group: bumpwright-auto-bump-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump:
    # Prevent re-trigger loops from bot commits
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (full history + tags)
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install project
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Configure git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version, update changelog, commit & tag
      run: |
        bumpwright bump --changelog CHANGELOG.md --commit --tag --format md

    - name: Push commit and tags
      run: |
        git push origin HEAD:${{ github.ref_name }}
        git push --tags
