name: CI (PR)

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Lint & Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install package + dev extras
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install -e ".[dev]"

      - name: Ruff (lint)
        run: ruff check --output-format=github --no-cache .

      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings \
                 --cov=bumpwright --cov-branch \
                 --cov-report=term-missing